### ISSUE TITLE
download.py中数据集下载地址有误

### ISSUE THREAD

**Issue by hjgw** [JinGyeSetBirdsFree/FudanOCR#11]
download.py中LSVT数据集的文件名写成LVST了
其中，DATASET_LVST_TRAIN.zip可以下载，DATASET_LVST_TEST.zip和DATASET_LVST_LABLE.zip需改为DATASET_LSVT_TEST.zip和DATASET_LSVT_LABLE.zip才可下载。
![WeChat Image_20200326165419](https://user-images.githubusercontent.com/42438605/77627857-8077fc00-6f82-11ea-83b5-c7036780312d.png)

感谢各位大神的分享o(￣▽￣)ｄ

**Comment by JinGyeSetBirdsFree** [comment]
搜嘎，这个typo我尽快修改，谢谢啦！
